version: "3"
services:
  nginx:
    container_name: dockernx
    depends_on:
      - astro 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse_proxy

  astro:
    container_name: astro
    build:
      dockerfile: Dockerfile
      context: ./astro
    depends_on:
      - nginx
    networks:
      - reverse_proxy

networks:
  reverse_proxy: