version: "3"
services:
  nginx:
    container_name: dockernx
    depends_on:
      - astro 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse_proxy

  astro:
    container_name: astro
    build:
      dockerfile: Dockerfile
      context: ./astro
    links:
      - wordpress
    networks:
      - reverse_proxy
      - wordpress_n

  db:
    image: biarms/mysql:5.7
    container_name: 'tyup_mysql'
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'tyup_content_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'root'
    ports:
      - '3306:3306'
    networks:
      - wordpress_n

  wordpress:
    image: wordpress:latest
    depends_on:
      - db 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USERNAME: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: tyup_content_db
    links:
      - db
    ports:
      - "2025:2025"
    networks:
      - reverse_proxy
      - wordpress_n
    volumes:
      ["./wordpress:/var/www/html"]

volumes:
  data:

networks:
  reverse_proxy:
  wordpress_n: