version: "3"
services:
  nginx:
    ports:
      - 80:80

  astro:
    volumes:
      - ./src:/usr/src/
      - /usr/src/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev