version: "3"
services:
  nginx:
    container_name: dockernx
    depends_on:
      - astro
      - wordpress
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - reverse_proxy

  astro:
    container_name: astro
    build:
      dockerfile: Dockerfile
      context: ./astro
    depends_on:
      - wordpress
    networks:
      - reverse_proxy

  db:
    image: biarms/mysql:5.7
    container_name: 'tyup_mysql'
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tyup_content_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    networks:
      - reverse_proxy

  wordpress:
    image: wordpress:latest
    depends_on:
      - db 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: tyup_content_db
    networks:
      - reverse_proxy
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress:/var/www/html

volumes:
  data:
  wordpress_data:

networks:
  reverse_proxy: